security:
    providers:
        pimcore_admin:
            id: Pimcore\Bundle\AdminBundle\Security\User\UserProvider
        # We use a custom user provider which loads users from the Customer class
        # The user provider is provided by the CMF
        cmf_customer_provider:
            id: cmf.security.user_provider #cmf.security.user_provider.oauth

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Pimcore WebDAV HTTP basic // DO NOT CHANGE!
        pimcore_admin_webdav:
            pattern: ^/admin/asset/webdav
            provider: pimcore_admin
            http_basic: ~

        # Pimcore admin form login // DO NOT CHANGE!
        pimcore_admin:
            anonymous: ~
            pattern: ^/admin(/.*)?$
            # admin firewall is stateless as we open the admin
            # session on demand for non-blocking parallel requests
            stateless: true
            provider: pimcore_admin
            logout:
                path:   /admin/logout
                target: /admin/login
                success_handler: Pimcore\Bundle\AdminBundle\Security\LogoutSuccessHandler
            guard:
                entry_point: Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator
                authenticators:
                    - Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator
            two_factor:
                auth_form_path: /admin/login/2fa                   # Path or route name of the two-factor form
                check_path: /admin/login/2fa-verify                # Path or route name of the two-factor code check
                default_target_path: /admin            # Where to redirect by default after successful authentication
                always_use_default_target_path: false  # If it should always redirect to default_target_path
                auth_code_parameter_name: _auth_code   # Name of the parameter for the two-factor authentication code
                trusted_parameter_name: _trusted       # Name of the parameter for the trusted device option
                multi_factor: false                    # If ALL active two-factor methods need to be fulfilled (multi-factor authentication)

        # mys_main firewall is valid for the whole site
        mys_main:

            # -----------------------------------------------------
            #   SAMPLE SIMPLE FIREWALL CONFIG FOR HTTP-BASIC AUTH
            # -----------------------------------------------------
            # the provider defined above
            # provider: cmf_customer_provider
            # http_basic: ~


            # -----------------------------------------------------
            #   SAMPLE FIREWALL CONFIG FOR FORM-AUTH
            # -----------------------------------------------------

            # The provider defined above
            anonymous: ~
            # The provider defined above
            provider: cmf_customer_provider
            form_login:
                login_path: 'account_login'
                check_path: 'account_login'
                csrf_token_generator: security.csrf.token_manager
                default_target_path: 'tools_start'

            logout:
                path: 'account_logout'
                target: 'account_login'

                # Optional: to keep logins of other firewalls (like admin)
                invalidate_session: false

            remember_me:
                secret: '%kernel.secret%'
                # always_remember_me: true

        cmf_webservice: '%customer_management_framework.firewall_settings%'


    access_control:
        # Pimcore admin ACl  // DO NOT CHANGE!
        - { path: ^/admin/settings/display-custom-logo, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/2fa-verify, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS}
        - { path: ^/admin/login/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS}
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/(login|lostpassword|deeplink|csrf-token)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_PIMCORE_USER }

    role_hierarchy:
        # Pimcore admin  // DO NOT CHANGE!
        ROLE_PIMCORE_ADMIN: [ROLE_PIMCORE_USER]
