_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

app_localized:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:
        en: /en
        sv: /sv

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

account_logout:
    path: '{_locale}/account/logout'
