_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"


app_localized:
    resource: "../src/Controller/"
    type:     annotation
    prefix:
        en: /en
        sv: /sv

app:
    resource: "../src/Controller/"
    type: annotation

account_logout:
    path: '{_locale}/account/logout'
